ansible_connection: network_cli
ansible_network_os: ios

ntp_servers:
  ntp_commands:
  - "configure terminal"
  - "ntp server 192.168.100.10"
  - "ntp server 192.168.100.11"
  - "end"
  - "write memory"


