---
- name: debug module demo
  hosts: cisco_devices
  gather_facts: no
  connection: network_cli

  tasks:
    - name: Gather IOS facts
      cisco.ios.ios_facts:
        gather_subset:
          - all

    - name: Display router serial number
      ansible.builtin.debug:
        var: ansible_net_serialnum
    - name: Display router hostname
      ansible.builtin.debug:
        var: ansible_net_hostname
    - name: Display router model
      ansible.builtin.debug:
        var: ansible_net_model
    - name: Display router version
      ansible.builtin.debug:
        var: ansible_net_version