- hosts: cisco_devices
  gather_facts: no
  tasks:
    - name: Gather IOS facts
      cisco.ios.ios_facts:
        gather_subset:
          - interfaces
        #gather_network_resources: all
    - name: Print IOS_facts
      ansible.builtin.debug:
        var: ansible_facts

    #- name: Print IOS hostname
     # ansible.builtin.debug:
      #  var: ansible_net_hostname

      